// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"time"
)

type Member struct {
	ID        uint64
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
