// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package model

import (
	"context"
	"database/sql"
	"time"
)

const createMember = `-- name: CreateMember :execresult
INSERT INTO members (
    first_name,
    last_name,
    created_at,
    updated_at
) VALUES (
  ?, ?, ?, ?
)
`

type CreateMemberParams struct {
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMember,
		arg.FirstName,
		arg.LastName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const findMember = `-- name: FindMember :one
SELECT id, first_name, last_name, created_at, updated_at FROM members
WHERE id = ?
`

func (q *Queries) FindMember(ctx context.Context, id uint64) (Member, error) {
	row := q.db.QueryRowContext(ctx, findMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
